project:
  type: website
  output-dir: docs
  render:
    - course_intro.qmd
    - reproducible_docs.qmd
    - OS_2024/dataHandling/dataHandling.qmd
    - OS_2024/Systematic_Reviews/Systematic_Reviews.qmd
    - OS_2024/Systematic_Reviews/meta_analysis.qmd
    - functions.qmd

format:
  html:
    code-link: true

execute:
  freeze: auto
